import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider, AuthProvider } from "@/shared/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <TanstackProvider>
          <AuthProvider>
            {children}
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
