import type { Metadata } from "next";
import "./globals.css";
import { TanstackProvider, AuthProvider } from "@/shared/providers";
import { headers } from "next/headers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const getUser = async () => {
    const header = await headers();
    const user = header.get("x-user-data");
    if (user) {
      return JSON.parse(user);
    }

    return null;
  }

  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={``}
      >
        <TanstackProvider>
          <AuthProvider userProps={user}>
            {children}
          </AuthProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
