import type { Metadata } from "next";
import { headers } from "next/headers";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { AuthProvider } from "@/shared/providers";

export const metadata: Metadata = {
  title: "POS by NPN Group",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const getUser = async () => {
    const header = await headers();
    const user = header.get("x-user");
    if (user) {
      return JSON.parse(user);
    }

    return undefined;
  }

  const user = await getUser();

  return (
    <html lang="en">
      <body>
        <AuthProvider initialUser={user}>
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
